### ISSUE TITLE
(C++) Eclipse Project Import not handling header files correctly 

### ISSUE THREAD

**Issue by RohitM2019** [wpilibsuite/vscode-wpilib#57] opened 2018-08-05 00:20 UTC
When importing Eclipse robot code into VScode using the "upgrade" function, any header files for custom classes is placed in the same src/main/cpp directory as the cpp files. When building the robot code with /gradlew build or the wpilib build command, the build fails because it does not find the header file when compiling the corresponding cpp file. This is resolved by placing the header file in src/main/include rather than src/main/cpp.

**Comment by ThadHouse** [comment] 2018-08-05 00:26
The issue is that the default WPILib projects in eclipse did not have a separate include folder, and just placed everything together. And then there were some versions that included the src folder as an include root, and some that didn't. So depending on how the users wrote their code, and depending on the eclipse version used, they could have different behaviors. But most commonly, teams did not depend on src being an include root, so moving files to include will break a majority of teams. We have no way of detecting otherwise during the upgrade.

**Comment by Ewpratten** [comment] 2018-08-05 01:49
Adding a warning / note about that would be nice. I had to manually fix my code due to use of non-fixed paths

**Comment by ThadHouse** [comment] 2018-08-05 02:02
Can either of you @RohitM2019  or @Ewpratten post your eclipse projects or send them to me? I'm interested if this is a different problem then the one I'm thinking of.

**Comment by ThadHouse** [comment] 2018-08-05 02:26
Its because that include is using `<>` instead of `""`.  That causes GCC to not look in the current directory. We will just make eclipse upgraded projects have a `-I` to the main src code directory. If you want to do that now, in your build.grade in the `exportedHeaders` block add another srcDir line `srcDir 'src/main/cpp'`.

 Your exported headers should look like 
```
                exportedHeaders {
                    srcDir 'src/main/include'
                    srcDir 'src/main/cpp'
                }
```

**Comment by nollchr** [comment] 2018-08-08 01:25
Quick question before I open a separate issue.  I have install VSC, c++, java, wpilib plugins on Windows 10 as well as iMac.  In neither installation does the Upgrade work for c++ eclipse project.  I am able to create new cpp command based projects and build.  Just wondering if I am doing something stupid?

**Comment by ThadHouse** [comment] 2018-08-08 01:36
You selected a directory to put the new project in right? And its not the same directory your project currently exists in? Can you post a screenshot here or in a new issue of what your screen looks like before pressing the update project button?

**Comment by nollchr** [comment] 2018-08-09 00:25
![image](https://user-images.githubusercontent.com/9668510/43871135-3396dd20-9b49-11e8-9a31-2317f5b050e2.png)

**Comment by ThadHouse** [comment] 2018-08-09 00:35
Do you have permission to write into c:\FRC_Alpha, and does that folder exist without a PowerUp folder in it already?

**Comment by nollchr** [comment] 2018-08-09 00:38
Yes.  I feel like i'm doing something really stupid because this happens on 2 different Windows machines and an iMac.   

    On Wednesday, August 8, 2018 8:35 PM, Thad House <notifications@github.com> wrote:
 

 Do you have permission to write into c:\FRC_Alpha, and does that folder exist without a PowerUp folder in it already?—

**Comment by ThadHouse** [comment] 2018-08-09 00:39
I get the feeling something is wrong with your eclipse project if that's the case. Can you zip it and post it here?

**Comment by nollchr** [comment] 2018-08-09 00:44
[PowerUp.zip](https://github.com/wpilibsuite/vscode-wpilib/files/2272457/PowerUp.zip)

**Comment by ThadHouse** [comment] 2018-08-12 20:39
This issue was fixed in https://github.com/wpilibsuite/vscode-wpilib/commit/4d90bdb783fe3dbb932917f7a0c5a6cbf267fb1e If we do another alpha release it will be included.

**Closed by ThadHouse** 2018-08-12 20:39 UTC
