### ISSUE TITLE
WPILib commands do not work in Multi-root Workspaces

### ISSUE THREAD

**Issue by webbbt456** [wpilibsuite/vscode-wpilib#195] opened 2019-01-13 00:34 UTC
After creating multiple WPILib projects and adding them to the same workspace, WPILib commands no longer work. When I click on the Open WPILib Command Palette icon I get the following message:

command 'wpilibcore.openCommandPalette' not found

Steps to duplicate: 

Open Visual Studio Code
Click on the Open WPILib Command Palette icon
Click WPILib: Create a New Project
Create an example C++ project called test1 (example type does not matter)
Click on the Open WPILib Command Palette icon
Click WPILib: Build Robot Code
Repeat the 5 previous steps, name the project test2, use same root folder as test1, open in the same window
Click File
Click Add Folder to Workspace
Select the test1 folder
Click on the Open WPILib Command Palette icon

**Comment by ThadHouse** [comment] 2019-01-25 00:22
Oh, I finally figured out why. I am attempting to register commands, but I'm doing it in a loop. I will fix this for the next release.

Code with the issue is the ApiProvider being created multiple times, which creates the Header Explorer multiple times.

**Comment by ThadHouse** [comment] 2019-02-06 03:32
Closed by #207

**Closed by ThadHouse** 2019-02-06 03:32 UTC
Labels: C++, bug

**Comment by brogandillmore** [comment] 2020-09-29 22:30
ok
