### ISSUE TITLE
Grey out "Generate Project" if options aren't set

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/vscode-wpilib#438] opened 2021-01-31 03:48 UTC
![image](https://user-images.githubusercontent.com/10674555/106374033-35bad380-634d-11eb-8d76-27a1cf0dee54.png)

**Comment by sciencewhiz** [comment] 2021-01-31 04:00
Duplicate of #343?

**Closed** 2021-01-31 04:12 UTC
