### ISSUE TITLE
Project Importer breaks on submission button

### ISSUE THREAD

**Issue by gbuckholtz** [wpilibsuite/vscode-wpilib#479] opened 2021-11-05 20:41 UTC
![Screen Shot 2021-11-05 at 4 37 36 PM](https://user-images.githubusercontent.com/1216916/140575644-9e28fe18-ea8a-4f91-a95e-269300bef018.png
![Screen Shot 2021-11-05 at 4 37 43 PM](https://user-images.githubusercontent.com/1216916/140575651-d8285232-592f-4f01-90c1-5c1a828a2d55.png)
![Screen Shot 2021-11-05 at 4 38 37 PM](https://user-images.githubusercontent.com/1216916/140575678-3a6f7a40-d3fb-48cb-88db-5c992ebc792a.png)
)
![Screen Shot 2021-11-05 at 4 38 46 PM](https://user-images.githubusercontent.com/1216916/140575685-d23a56be-aa52-4793-8d77-9785ddb70dd3.png)
![Screen Shot 2021-11-05 at 4 38 54 PM](https://user-images.githubusercontent.com/1216916/140575706-c3873e11-3af7-4db1-9444-5bfadbee27a3.png)

Then the "import project" button is clickable, but nothing happens

**Comment by ThadHouse** [comment] 2021-11-05 20:43
This is a known issue in the 2021 project importer. It has been fixed for 2022. You can follow the manual import steps here to upgrade your 2020 project to 2021.
https://docs.wpilib.org/en/stable/docs/software/vscode-overview/importing-gradle-project.html#manual-import-process-2020-to-2021

**Comment by sciencewhiz** [comment] 2021-11-05 20:45
Duplicate of #454, documented here: https://docs.wpilib.org/en/stable/docs/yearly-overview/known-issues.html#visual-studio-code-project-importer-fails-to-import

**Closed** 2021-11-05 20:46 UTC
